site_name: BookBrainz User Guide
theme:
  name: readthedocs
nav:
    - Introduction: 'index.md'
    - 'Getting started': 'getting-started.md'
    - 'glossary.md'
    - 'Style guidelines':
      - Overview: 'style/overview.md'
      - 'Entities':
        - Edition: 'style/entities/edition.md'
      - 'Language specific guidelines':
        - 'English': 'style/language_specific/capitalization-en.md'
      - 'Style process': 'style/style-process.md'
    - Tutorials:
      - 'Add a book': 'tutorials/add-a-book.md'
      - 'Merging entities': 'tutorials/merge.md'
      - 'Series entity': 'tutorials/series.md'
    - Resources:
      - Reference: 'reference/index.md'
      - 'contribute.md'